Update __main__.py
Traceback (most recent call last):
  File "<frozen runpy>", line 203, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Plex\Torrenting\__main__.py", line 21, in <module>
    d = next(Missing)
  File "E:\Plex\Torrenting\Scanner.py", line 44, in Missing
    show = Media.Show(*ReadName(ShowDir.name))
  File "E:\Plex\Torrenting\Media.py", line 176, in __init__
    self.seasons = [Season(self, *i) for i in Omdb.show(title, year).Seasons.items()]
                                              ~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Program Files\Python314\Lib\site-packages\philh_myftp_biz\web\omdb.py", line 131, in show
    for s in range(1, int(r1['totalSeasons'])+1):
                      ~~~^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'N/A'